package utils

const APP_NAME = "goenv"

const KEYS_FILE_NAME = ".goenv.keys"
const PRIVATE_KEY_NAME_PREFIX = "GOENV_PRIVATE_KEY"
const PUBLIC_KEY_NAME_PREFIX = "GOENV_PUBLIC_KEY"
const ENCRYPTED_VALUE_PREFIX = "encrypted:"
const EMPTY_VALUE_PLACEHOLDER = "__EMPTY__"

// Error codes
const OPEN_FILE_FAILED = "OPEN_FILE_FAILED"
const WRITE_FILE_FAILED = "WRITE_FILE_FAILED"
const FILE_NOT_EXISTS = "FILE_NOT_EXISTS"
const FILE_NOT_ACCESSIBLE = "FILE_NOT_ACCESSIBLE"
const KEY_GENERATION_FAILED = "KEY_GENERATION_FAILED"
const ENCRYPTION_FAILED = "ENCRYPTION_FAILED"
const INVALID_PRIVATE_KEY = "INVALID_PRIVATE_KEY"
const DECRYPTION_FAILED = "DECRYPTION_FAILED"
const BASE64_DECODE_FAILED = "BASE64_DECODE_FAILED"
